# Environment variables for different deployment stages
# These are examples - adjust according to your needs

staging:
  NODE_ENV: staging
  DATABASE_URL: postgresql://gafus:staging_password@staging-db:5432/gafus_staging
  REDIS_URL: redis://staging-redis:6379
  NEXTAUTH_URL: https://staging.gafus.ru

production:
  NODE_ENV: production
  DATABASE_URL: postgresql://gafus:production_password@production-db:5432/gafus
  REDIS_URL: redis://production-redis:6379
  NEXTAUTH_URL: https://gafus.ru
