# --- Stage 1: Build stage ---
FROM node:20-alpine AS builder

WORKDIR /app
# Отключаем интерактивные подтверждения в pnpm
ENV CI=true

RUN corepack enable && corepack prepare pnpm@9.1.0 --activate

# Копируем весь workspace (монорепу) сразу
COPY . .

# Установка всех зависимостей и сборка
RUN pnpm install --frozen-lockfile
RUN pnpm --filter @gafus/queues run build
RUN pnpm --filter @gafus/bull-board run build

# --- Stage 2: Runtime stage ---
FROM node:20-alpine AS runner

WORKDIR /app
# Production‑режим и отключение интерактива
ENV NODE_ENV=production
ENV CI=true

RUN corepack enable && corepack prepare pnpm@9.1.0 --activate

COPY pnpm-workspace.yaml ./
COPY package.json pnpm-lock.yaml ./
COPY apps/bull-board/package.json ./apps/bull-board/package.json
COPY packages/queues/package.json ./packages/queues/package.json

RUN pnpm install --filter @gafus/bull-board... --prod --frozen-lockfile

COPY --from=builder /app/apps/bull-board/dist ./apps/bull-board/dist
COPY --from=builder /app/packages/queues/dist ./packages/queues/dist

WORKDIR /app/apps/bull-board

CMD ["node", "dist/apps/bull-board/bull-board.js"]
