# syntax=docker/dockerfile:1

FROM node:20-alpine

WORKDIR /app

# Install required packages
RUN apk add --no-cache openssl curl

# Copy configs
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.base.json ./
COPY apps/telegram-bot/package.json ./apps/telegram-bot/package.json
COPY packages/prisma/package.json ./packages/prisma/package.json
COPY packages/queues/package.json ./packages/queues/package.json

# Install pnpm and dependencies
RUN corepack enable && corepack prepare pnpm@9.1.0 --activate
RUN pnpm install --frozen-lockfile --recursive

# Copy full project
COPY . .

# Generate Prisma client
RUN pnpm --filter @gafus/prisma run db:generate

# Build prisma package
RUN pnpm --filter @gafus/prisma run build

# Build bot
RUN pnpm --filter @gafus/telegram-bot run build

# Create symlinks for workspace packages
RUN ln -sf /app/node_modules/.pnpm/node_modules/@gafus /app/node_modules/@gafus

# Set working directory to app root
WORKDIR /app

# Launch bot
CMD ["node", "apps/telegram-bot/dist/apps/telegram-bot/bot.js"]
