name: Build Web App Only

on:
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: "Force rebuild even if no changes"
        required: false
        default: false
        type: boolean
  push:
    paths:
      - "apps/web/**"
      - "packages/**"
      - "Dockerfile-web"
      - "docker-compose.prod.yml"
      - ".github/workflows/build-web.yml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: asmtv1

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Web image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile-web
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/gafus-web:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -e
            echo "🚀 Deploying updated web app..."

            cd /root/gafus

            # Pull new web image
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/gafus-web:latest

            # Tag for local use
            docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/gafus-web:latest gafus-web:latest

            # Restart only web service
            docker-compose -f docker-compose.prod.yml restart web

            echo "✅ Web app deployed successfully!"
